# Generated by Django 3.0.1 on 2019-12-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifications',
            name='unit',
            field=models.CharField(help_text='the unit of specification', max_length=250, null=True, unique=True),
        ),
    ]
